---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    tunnel-token: AgC4QgnRRL9wQ64TGoX/nzYvEuDPAwbniAsP36Ltm9dzJklkKEUDob5UQzvZ6K/zqlq7GVjNvILggm0hwfGceFiHAPbABS7yudRCL79XTktJCqd6Q3HI8ePXtQ/NLcbP8PXEINI8ldJNCrS8+Dj8qgVOrdOZk9RPkGpP/quOYyShF+zBbNfZMqcxlgINvC5A7oeG3ZBk+Viv1qu+6eTWDbVkLHBMWMZY5LREINaXjniwzvD2e6b5u//eKk1TylAaycbPFJjDSQUwNHRWtQQDuatlJxfnk5AUiD+yd3UnrAU6MV1P9n2P/Yq6DwnElRlUJBpInur9Uu0+Mpr8Bl9lqNbk2RAU8Sf7HKwINoqUFerC8Nt1WsqP32gvKE1rWLbNhvZQmISA/ulF/mIoVgjr+V0DpJad9QQH29IH9sedBBlqhuUUxWcDQgTJLdydsnYJAvDzf5i92Bk4oEup/WpwStDuUVyadYfcAaObrPpzXsqaQU87ck9bxhrepbBHpZQ6EfDgdPxxlBFQGXenhj5z6TCsND4dXFKPP/83+NKra9crf8iiFzj+I6JCvYcwdDl8tqw40PZ3b2/8OxB8beCEmVgVHfuW5cpNW7AyZHg0MIGB/OYUKhTFO1Av8iM9fwoHG5jqu9Qs6fE6VyldzoUpOYq+aTXBLXT1eeBwB78uOQHJ0J83PtvVL4SEFXlUUvsWmMLCuLSuWxaVUtDrTRoGY6PrRClK8qcDjOkUKQCQlQroxINo7ojG3wYutQciRiom9xX8VdCw7ytobxsduu4wrNIA8SUhNec9yJsCQ/Vkkty1RlAMJ2QKDb8YKMA/AyF5JlONO3z0ak1mRDviN4Rn5OPD9QiTrH5YY8Mc+98F7a+h3xzM9XENoEu+4ZSQwdQqVbUQtOVYfebNDnOTMBSVQIhsvHhdyXsGEO+w7/hJrCU99A5bL0mNHQaw
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
