{{- if .Values.certificateManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certificateManager.email | default "admin@example.com" | quote }}
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: {{ .Values.certificateManager.cloudflare.email | default "admin@example.com" | quote }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: apiToken
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.certificateManager.email | default "admin@example.com" | quote }}
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: {{ .Values.certificateManager.cloudflare.email | default "admin@example.com" | quote }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: apiToken
{{- end }}