apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-init
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/BenedictusAryo/k0s-cluster-bootstrap.git'
    targetRevision: HEAD
    path: cluster-init
    helm:
      releaseName: cluster-init
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true