---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgCC278cIfe6M+rqrX9J7/xJ3bExetn4oragD3lSPDoA+HZpmhFml4tYIVHUMBkdNTReJAFkkeUDaFOi1TwpVHB93PWYPpG9iMfo41GzReLoZ0mG4m6bRquFOR3Hshw+VzT1fwQslLpmp28HCzzevXKcaBUVJcBQZ5LKbn06XetFW3EeqqN3HMXuqhDOSdAQzHyLz1ZZH4cYV1w03sl/QWAyp6rHze2OZEUM+vmdTP6XxgrCS0TOaQdgSuRFtFnxQtzx6S0nW2i/BxaL2Lsg17y/h4Z69tTQ7wUgFOqzSLGZ4XWlQ1XNWZQ75QA2c/2YWKlsB+5fxWCBv2UG+FiULmv7ZkHrfXgCknCrgVXy5oQie421vieqxiGmL3XRaLk7o7ZWrgDtRIRFBCwzmmZbYZ5Fd9c4uklS0WcbuCuaBfukbjnHyO7pdlDpLemT1Y2cB9Mk567AZ8/qu2kh5XKRjjCaHzO/vnepNUj1dAbHpgrXE8rP/xijQvi/ZhPVDny/BUdBnK6t0HtDb6VaPmtyNXUSGYKW7+r86OLnRFr+vnlWz+LmBkulx5HxmqKA1A6m7gWxH0pZWKNOh5M84PoHcGFBUXeX0JlQGivjFT01x3K4nVvvdq9hgwsCaFDJA343pEIC2Lryo6Z9cDZucKhm1VZgNJlX0Q3np74Lwj5bGEdn3G+5vMwaclaqGn1PZzCKxrhU69i44wU9f32ZZ4YZsz0wTLQENOQorF2f2Nzx3kIBGkH4meHq0FGiiU540wZUYX6Jkg7YlSx+GecxQ0c2ub1tDK9oPJxDOXD3O9+5+AYd/N84Ncc5590Sudw40fw15tpNhayDlKmNO3lCQjgGzKRtQyKRLJWnAx4OT2QW2a64A0ql7WAyRH05jE2aToTEjHEdEc0Lwcd/fUKhFub7zhxJoIzU71NWrgrlClLz+oSsG55zmzyfor7E
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
