---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgAEo3RzaegV6A/fqPYLD1ACIvkw0wHfRKFDcJ0Zyma/QN2vZ91oPs6OExi9GBCrpvM4f2Gq0fXPbR8jM3wNND/6vCGQmWByw64soN5+cLTWL3jshEs7tyTbw9bXR3h1MrK9wnnY2YcTx/GuOCotTowg02uY+HghzTSRmRvmBrlspq2pq1aUna6XPneex//lwHUqGbaluz42W9oKFwLlEPeEgIG2GvBkVrxMbcp6Eaz1S5obE136QkVnkO96fig/qTFZPBf/tQ/qVymiqePpDAOiUF3QerMRZNR7Tbi6pcBLRPsqOQGbv6IP2iGJG4+Yar3j4QbugW7hyDhtsbraqh2OoqlmEX4iipsiF1imbykKLp6YUN+nTm8WRlCmoMjh4bwBLdTky95n6T6lYxa4lXDio6U0X8gpfFm6fgZkuTa1YUlZt8PMrSCC/TaeaJlO1zS/M2p6cUyTaiS/1IYewobzq7qKqORqZydq50L2HpGLsMxGSVj7AJhAzPuJr5v/25wSBDlD/Py+xUhHbFbuDffXWClwDJCLWWxGoEYdV2E7X/uBXPPYbV16pjQxxdCaA8KMNAuVTJAEsnCxZ6Zb8LLW+oKqjH3ssLGhiXvTPyzPVI672UjcGCJN+5HMCNBZ2GF9g9Tb/bwB+OUQRaw7FPkPRoAKYvgkum1ysEFJdoTOIEmt54sYjYaUupHvDFFFbYA+Rbwj1KNKNEeG0MtKXtcarm+El81k8idVAT3nGqlI3f+3frSDEqY7OA+Z5dBVAPkcF6e/8ifTVmoDRVmY5EVxJYQCQb5IHgA3P1ce3+eCegjyj71NXRI8kwmeUPICqSk3Df1iJBsjV0G56NHJNf5ixHMAhWjSdh0iWphyUzQvK2CFFpIYbvRbFmZ5mDVJ4DuhFyKCJCEyp9Jr3c6xkq/RNEPnTxPvNMoasGUuD/IhU3sl6qZSEZct
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
