---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgCXf6obIhz2pDGNfXnhVeXGV9EzxHeoxdcW/Wgnfy/NpVPeU20k0l8kBjDabqN6kbkJ+UxqAJrSOjVZTk7GETkDramclodOOqNlwDDiVRRZWSfnY/d9a0nd3aAm+9yfely1GLxQ+eLaIQJHnMNCWtapCZru+cgDRzv4jy6vTApxIRc1dKvbBw/ZiKFigDvm3KgZuzH5iWhqAi3+RdQ1/74DxA4U0GfaHDg7nfwKsE03LtyBKQhWOgNJx1dTMMmMd7E3odIC/CiOc0UJnKpi3Yst+Ix8pa/5xOF6UGlc7/uBaQKslkW1n18oothaAM5CeImWHYM81pq3ImHM0v55945iUfyITHOZWVFxNbX8FmD+6ySgMjr8dbPCyH0BdGR8ZTdOcjpJIbyGrWYDnhjbfHV81V9DSFTfQ70R5mHhBOWWwOREFDEUb0nY0MqvBLcNo4mag0Pklw6PRXXq526RJHqMcJIskB1Lyu6VXn4pNTDmJ2VFhZNK8xenajzsnALdTve968Hj1m3Fe10pd0RXX3M3ss19/9M71PTMuWm/rgpFaO77cfN7VnaQhR4QEJil6vDc9jdwPN8sXIydNff1kRLredD+h0bVsZVg8YkNK479dvgJu71+5DWVQN0tiW+HSPlBjWt2rhguee/6E7I+Foj5KkHQaDDB6T5S+D4KlC6ua5OW8NWKwyTgsVd8iYzM+tqVFXCoubpfxkVunswFIDveKZWrxOyPgX04VAXugLrkqXXV7fMumXRqFxTETxcWp6Z3Yq5bbS4X072XRrVcQ8V7XtjCZtjLKa1vLhG2BsXyyhAoJUhnvuMp3vt4j0emdSBELE8ty+SAQ5KXAZZdLkVoDovAxKnbahaviLztst3DnNHM5rQOmCOQFIBbAtEvULcWOkVwFAm8+NPWvvN+3AHRmqhUSwIKCNIycldpxDPPaPsUa5d625Wl
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
