# Cloudflare Tunnel Sealed Secret
# Generated on: Mon Nov 17 08:15:30 AM UTC 2025
# 
# This secret is encrypted with the cluster's Sealed Secrets public key
# and can only be decrypted by the sealed-secrets-controller in the cluster.
# 
# To regenerate: run scripts/generate-sealed-secret.sh
{{- if .Values.cloudflareTunnel.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel-token: AgBFV8GD75Ojq7RbXsUfyRN7ZRxYWDs3cBGdnIxwD+tGJR62LuVEJ+8j/+BjtYWWt6AyAuKfNAf3bExqRfjR6/C5pahgM+TO3j1+ZruCCaJ3MRAZ1b/Vzbo6ugH2/VkxzrbHlhbmOvC2v6EzO4r3iXIp18bxrmGHVq4cjSpge1Wpjnpny9Zbq6gfZCoolrHTl2uYQ9medzbOcnMVDs+yZa07DP7XQLOJVw4zc1iuxtD5qiR36YLeQwUaWFEV8qFBwAPeY06YPhVT3KFfXuG1rJHJkvyyhHXg0lZgT5dbQ8GhVxHKJL2lBOQKmgaT3gkcd3H4jfD0Rj419FZM9deKnF2RPqLQyJdvEWABXFDXXLYorqMVb55w5PdUv0SmNgEVQY4mCecL6r3u/a1pVeq+ZvE1zKn880DWyXtFpXHd3CUBbblqJ8P8D/kFuyP78KpiB/jiyG1jpXUX8/XV21R6eELcobt56jz1yaMg8X6of1zneg6o8754L3DkXMh3wf60H2ALdWdo56eMjN5nGeeUhNRNjfoycfHuE8LZPoX+q738lLGgUMToEcgWZiB83fxOLbBgKiGaRfJix/iSqX1fiM4gJzYEYF22xqCsmBG7HgiqWGAkh1nwtvGsVZwDdTcGogeyeDd51LlLqj8UCkzhENbn6+mNotJ+gNns1HgBWhSUZOUCiNrdiYVjXBLo+5B1p4bb5137JfJ6Ydx1J3qXvk0pb3rlGibdeKjtdV0CEKEq9i5PSs997JJJ5194rADr8qc0sCA5vkBp9TDKqwJ+F8PVaqgXkbjWYRLO7/76uigHQClKjWCbqaCQAY3JftBuKYkcMdYdTgGdALP7J6QfziIDKsNBxVHDiqu4v7E40WuVUoguNa/mMx4zyk7v58XdZMhFtxc6xsGxZbcbPXLZ5KpSjDF9YsZdExCTbZfv6avK0XJFgTRlwtMG
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
    type: Opaque
{{- end }}
