---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgCtGsjerd3eM36Rrr6c1OtKvrHwQapO5EdbySkuyCoo50krYUsqUBn8K84F9NaDDRtz3gV8mjPq3kEK1uO52mn4eRc0eW/+DoMhYJD11QjYImq0d5kJa9fpIY5WezPBFca8lPj3Fztc0hbBDvlIgulIXsUrZndTGLx+OG2f9lLFBS1MAlyLPI7yXej0wOcK0mgoEnXxIFHZeoYxL/YZtjcDWJ/z0HAuc9MivBcaLjs6in5c2cptzYBuGIG54BMDIXjRwwfFD9NaCsSVsbL1hiFtT/sYWZVMP/OrAJQklJ3NpY88gJ/leqaLrfeTlS2MrKMPUi67zcf1aF4owAZ+bxav/iw/AzWOptG9AsmT/Ej9NTRUvoVJ7zicNahAvFwAVBjjv9vCYwvTL5vBS62eD36rEONCKWBYzcnu8n1Y7JSrOdMu2u0RMrdGkcOPE7SXkPp7Pw745LUJIU978Jp35wTZTiV3dKEbGJD5j+h6rteALeLsmSTm4uT6c2kLtP92FBw+NDrn/WYR8v1Q5MxRyQGu9fYt5I2HFphrESckPneFztIiO671T6WAbv7ct6yXJe7g25MnL4xCtbXSIZfpfV1CopDGOwSN4xFGWgLg6vFj2S9aDMbFPanWb3VVLivn0dsbx4Ml6WDGrSYLAqj8N8lXHM8MRe6+5bX9N34vytkgDP+yVxOcxBw3fOrD3QrX3TKmyJyYLS7F/O5fZy8cebf+Uyx6R5u13GIjKvd+N5/SFgTq9cDOleDOKGbunmcVh6t7pkgBKEY45dXqhqlQBiGXvcPSN0Cefpt3990or9CgVVlHXC9CIYxkw4QwJhJRTBbXl2qd5Agh6EGtrXM9SzDAwwD0UMndcWdyBpjhvZjFjiPEdozVr/IlFEgr/ixYXtul3bfwd4zg6mz++BUOtVzYmg9dSMpH94buXKhMhnCRzOmqAbLnBMEi
  template:
    metadata:
      name: cloudflare-tunnel
      namespace: cloudflare
