---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgAHS96YizkcqQSdAhHNoaLTHl/Mkekny5vPofocF4NxElTI0mcljcrFFzghhq7PfMOiHKqClqxbKV8xgrhBXJSEvo6vt1tsujg16zq+PyfaNgrv/V+NyX5wUPRUIuHdGWrqmhEg0Sywi1OufI+kfoD6elvWU5RsdomeCfyB6hI3um5QPY5d7dUVXwm6KWOBsKzgFdQEWMDxe3/wOXtouvgbsWwXGIIhNiwl+D97qDwEK1Wg2KiqZPuc3HwbDwiCUBBXWhDuv8/aVSraqpV+A3++82ANf0A/5XpudWg8InqAt8s7A7Wo6lXKvoPCjASzKftza6MrPArrK6/GCC16ku4jD6Mkq9Wo6e5A8lVbktpNPKalK/w9m3x39e3g+5JW8C6aUWNDEqMIgHt1eIVLmOapy67XtCNo50jUuqh44hKM32tVB3q/CP2db1cDxnQrh2b4TmwXMJTTJdT58tkK2M+RMnUudnfP8cl1EGXHgY4l4ffliX4gQNBlD1680KdzPmEwG2/bqM5bVBtRXkWKbVImmf02s46DJWvqnZAb/sgGM7gnPYZLMLZEVzuZKLgM0iBcbNDJ8elCiaSOBTlgg/aW+Ya09HzABtwiEwfWbrzqpHuTzlS9b9Q8EjkL0rOfCWUzkjdXbKhNw1DqDNV0JDvSKPQrutf3HVi86vAF4CbrUDDLmzPRzhK5CixLIDLd62IOWtbBIGXQAxuOS/72uEWcA1zlP0RibYMF7iTdSp1UgF3Df6+Yox+aE9//7HTXB6ObdCuSLb8qiC9EYoj4Lx3t6U7V9DVZMJD/k3V9HSuEEXCZX9kXi+u0j62gP11EnfwkYu1yujQgbj4n12WTbAbK+G7ItUq7g9ku9BA7mNvbGNakzzeL8Nn/cgOGpeeGYiKvbip85yFP5rVbGhjYxKUnvD/AL4B6eqNAq0hOCBiTZFhl40lg7OQP
  template:
    metadata:
      name: cloudflare-tunnel
      namespace: cloudflare
