---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgCPOSJycyHOOBjYDyqb9nxLlTIWPx/3dcO/utaYeNGClo0UUnKoQQW85skbm2HgMq4zEF7+DHkPr4OqxPfa+5+FGCol0wJzmEH4FkebQhXffuyqVGplw7DUQSRZrQcxioZp73DZZzeqo04FCuSGFgYJ22HWuCYWf0GjdB4mhaKXwQnCY6U1wSyWZbdnqPZznW25EV+VDxc2Y1ry+sF9f48oeFqh++INOL65MavTgSOVqE0/fW9sfYzZhm+SO+pdzLPJZk60zad8cTc70o5N0BRbZALU9vKbwFKC+wMOgAQBe4LejRUFc5HncmS2Yr1AcNHs6bZuvciK5LtDXOgzJ01YwQqJR/GVv4iZVC5iN5ngfM7FKXDMF1XWN7zBPsTnBAlGvVcXa41dtQeXBpzvmJbqJfaQggY4462sWS0ExvI2OEllTnK2MvEBbMIB2CW5U6zoYXz6Ba3j4jAus439cevt0K13rw/cg/xP+7fmTQaz30Lq0TI4yFxBvaQqwtC3mZz5uE1+BdU6U9wxcQYGjnn0gWxm6NBsCeY6rvZxJir9+mBCm+loo35lQWeJVzzI+bRa0aFSMDrPYSXWPzu+qJtXKoJ8BpWWTw2tc5RQySQgFWf8ToVsws2i99lkqvztn1CoKYFBzFtTJJsNLOHKgrqiL3546LUzUGn66oUx9GEKA6N9dUlLXmBHR+36/Hiifl9KsbAKna2gcHt90HQeyrRfpuNpxwphvFxTGeF/kzcgO+U/VJ9L7ODW9uNDqgwWLvYx7RCkbDGvmc1qx/K1fvEVMbWwqrmaJxCsXCy1qW7FT0bM/oVv90yYVsc6MEm/+PWPdEIYFCnE/OsR5EztFIMDEakZxrQo+Mn7Bh2OQCaCe5RFgwjKrogd8cz4sNrSB/EbXRzZqRKMnKn84mvI49DztOEKG1FjCeLNroKLmvtgvbCQ9ujEfUP8
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
