---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel-token: AgArVi1Mm/+X9b4zazv/SZCI5+GUakZSPRdmQ8eo3Oph8hU3Gn/k0oyaN5/c+CkkOxGB9gOk69j+duCqkGWWcjNpJ8YL9hcITHIaUPFqxnR2ZUa9ldYE8KlBIsjuiTRgWIqrmbGqFdmOu7trjVt7R7wSAKRU/fhon/8ZO+85IJ11omoKzh2LpLmzvyJZpiLh+LU65wO5h7S6NksjCm2xW5dU1BkjeJeQqr3gKtHW81fHSPXv/st/kLL0IV1NzmVTiH5/0z34vfkL5D9vU2XJQtIn/iOhBByrYJX74+c5VzKVh2Fbpr7Z4Q0xNnJjZur1EDCUlbAUgkS5b5waGyrIbF0VauOf6DgkrZ2vOK5jXA9/VpYQgJdbhEejOJtA3FnMfzTVCaeVX6Cuh7tarZx8izDYJjBePoCtmhdBXG9Z85d+J0uMqhPcbDB49HUOMRLfNBOKkIHjxMqRSDxzGB6bY4rJm8SDZyOvb+QEN7umT6xw5jWCNAyEwBV5B7B9Zt+9Phr7yVzEl6+YpnBWmoatWaeUBhlB4RDo/D2A152sU6mk8+XVkUuLoyQ9kn/yiAyqLtnB8tsJaU7Cc2iTJzlyulkPX5WTetKocsxYLN5G6ulSMblMUdGawJKHismI5m6SQDdD/0GOrdGeRR8dS55PLuNnyhWSlRDhUOxsIsBzdS9r3svCof1el0qbW4kcv1+REdXFg7tk1auVvv4XHY1cn1uWn3y9GDoEEF/5WSskKeDdHYAPwoH9U/vtbHPzsDh1yoJ/y7Bf0KuEXKY5iI4mo64Px5f0KnLygb56h6BCeAWBwSsO2qUELsvZ1M1sWs99E8OAPEUn+Wt0+55SwcaF72v7YmYMvjS0H2j9a26h67FhyGThQ88GCT8VGGlHv63f4BJwyUh11/nnTfjkz6eMAXGGlR0KjrQG4yoRZKDvm78BvIRNNnVvQR9r
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
