---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel-token: AgAfnlGbpstYH0lzVIAqShjnUswdexQElMmWKctaoQP1K/QLhci2U5zdd456VZBGUcPpC3FLdGoUnDUI8rfvWef78gonoBmswq26FHw27bA+n/w3y8RYFHMrsARKpPs+XHmKqhOVACKnwCotHwtAoH/tEdc+CmOIBWhGWxX5Kp6+6yJYsRJxCfzycP1olrF7Vw470puU+d3hbmQsnIwKeZbsPGu/GR2nwgmTLFPSGdhrz9W9qi7SIMV+C7QDkXeQMtng99a1Wa9MtTy2Y3kmqNxZ40lUOncy+Vvjl5bYkR9DsSaB2/iGY/yRT93zLxll+tgXqOiS50nljrwry9rdz+PkhQG2wIeslWLPh31QNgvvCPxzs1nct3ujHXTJAUWL5IjpasKMrZIfUWBPPSAb3fJuzNdz0qRXh329W+7o5fqWQuR+/ExCgUy3Cons2/JFoHI9CSTjpqTv5pI6ZLqcNWvMn6LLourtSVVWxGqUzoH4HeX/6VWdIu8f5Yk0IyQkn75C5OqDN0+T5QDhKCzu7+qMbln+Qlru4ua61/74opMwGklHiTZZwAa/cfiAMbheQiQedQGXLe677QAAwB+J4KjS+Z4nBQaXUpb5JQOPkfPOZF4Mt+qedD9Pd7iuLXaiXalycaPqdhmMlj6e+E2E29UTlvP17FcVBsqrjp8EoONxYUn7Q0hj5C5tuqNitF68XW0yc/UD/NqJQ84rNwS0xRr3Ci8ZlDKe4Elk/qMiD7hjTsMQPLk6ogRhpz5snuGsi5coVCGhXLnra05S3kYM1eXskqY7f5FnshISkS8xW2jsn+cwvrx7hamNVf0RPwA/ywNpjSFzotMx5/19g2ZlCLBjjNbV0XQtbUs60a+eI+l2hchnJ9xGvPnzIT1xsEwR5s1P+GBfF9KZNlrSlv9raqaJfvTqXVWYVqikvi0+lg/YF8Vc1feXPnPu
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
