---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgBjFtWDzgY/YxpbI5I4OajwTGTeXanrS/dfUlsoAENr1wKQZTbcn6aLSbTPYdA7pMjmGsz/RkYimmngy/JYM3DjfKt3aP4nRkny1KqLdE/PrRSzSzMUchEFMWyCxYUVHWLeCr9Qw3UO8rRpL2pXPw20ieeusOEFy3OWQE1QgXFu+qsCRvTUXF/PIZsr/IBkI/phDzQQhPH//ynWyTow+ApP/rbeEhW3WG0ysC84r2djaDPkJq01o0jVSc+Zq8ieYHNqX3MObNo3RTliE1/SbyWrMMHyxzyMjkVWEhUFPhzkR7Kscgh0nA/7a85UkyslBiqm8i4BUKnfwyu7I2XxSN5leaaBLvVT0hESqi5f/PSaKf9LAdeTfH1slfcmO1dhMC6nXeaJ6wSowmfYA+BgZWaYiIX9sbqCQGSqQFzXEURwdXaiZktA/VSd+GUXBRGp93zIBZDiuZF+PdfSoQl9cUSVL9MRmFCgMgfxKe6LQJFtoKJnopX81yUR98/D04v62QfNqL5Apa0b0O4dQJwLpx/hGVzbWN0BHBJXcjkL+AWd1xWmaZ3iYrHSmJZgmeY0Yig5JFNhpQsovX+Dq2oy7bUCQFIyszjUKdA6ClElP6mDggr9BGXi9tUgH/HbnidobtnqhPFYK7B2iEvyrPJgk1lbsbBDSeJyApe7Hnh+oqPSLojRZ9AnwF7wnp0tEGYY/gxtOV/O/XhD92AUOIH8GhSK0JFCPeza2IQn9zDqbqpdM8JDKCyQbOFWU2w6ot4fHl1mDAvUshbfnT6YBLfyoC8bISaUGjn69tT6+CBlwtsPuPsIm+03MtbB3V0cH5iWlRSxscmHXyrlcMrFhJXJ8d15BfcjpaBz7E1j7nGpUs8q81CaPdpe2KmIOBmoHllRyZY/subkcHqlogXTfFQ6qPftopnH3DOcLUWNlEMXMahQUJEqcXDiC6UB
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
