---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgArmUOmG28/cOTe9XJPRP5c+BEcPQUYAq0hKt/9QG2ohZWE3ZMIyJ2nugEy3N5fU++WYjAKrvuSXtCVxmUo3FN6c780CnWC7jWt9/w8q4boJeM9lpN4qJGJdhXkE0/+5wmzsyuzxDESVtXsaeFMpaVKIC+DcoQSOZfrm2nME+GSBz/imxqGY2LLXbQDTy29x9kSgEj5OGxcMsph5Pkvh8RzMfNVGf37ISkiW5FqlBBKdlDTFZqfG6lcKSJwPZcTk1M0XzyI/d2Gea/H8RJFI2nYmdOwREQ/FUZZEKCM7j50kqKm/XILcitRW96Ewj+Kqxtmn3fSSihmNkYFNEjGs8tuI8hVzy35KCCKuqw/jUhuV5rmBSF5phgxHnGUhNFNfWUueo0PhjVnH4DP0mvIrB4fb8OaEAP2vCfD4ay4yyCxqURRVbYLwlTkQ6GghAIydivLqZ1LdDS0tmFkeAJ+7kgIho70CfPl6TZ82QGBXcS8/lHb9l+Ab1W4kwlaDzYGs6tjEm3uGWpu3CLDeL9xvaVhsTS+1Q22UV52tD2qbz88hJvlMEHVV8OBKW5Zddxq19eJLHkBeDykzq7dzxxj/Oc1erimuhUEv49kTIeKBNuOmQKr8JxjBdzXtuWJHU1DXJL9mkK2FwiyYWA/cA+Ise7XdsPGOdQwNPV6V/nTO+rMP9HjYYSLqX1Vu9kUKcb0fH4gfFJLsH+ddpdLFJX3XN0CJGVfdKiOpiKei7+u1PUd1CLU1k/Iwu9ZWAJguTlMSl2uhMnYK267YkVSwAbTSRMOpYBJpaQYpAtNo0RdXBde6sBKPDDdTa2Qcsl2H/oFybCAXAR4DG9feiC2t4TFZX5I9uEiMX1WxOkSPYa7vOEx+H5HUuLNssHHEB2OZij42BuYo4z/llNdnnDj9CstOYu+8GiKI1HxSjEBEX3uR5Pz8rtK8jGQNTD/
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
