---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgCe55jY2niO6unR8JEeL0GTYXost5lzUYuvG8S8YtJQVW/QPvMXvUYUi++56DwTpLh1RHePKZc0f5C80Pd25nXYlhJknDQRn8YgBofd/CjFlQxFZ4X/VdbEiG+sTZ4JDGOY9wBQ09BNZ+P/LYyLa3Nwttmvzx0LuHwrPJ9/2QkWhCeVP2KXjsn8ZO3C0DPOcF4IBl0X9xJhXzM9wTHKxPTFqpB9+kU9mo2wLwM2Y991wN7q+c9IdlOnPOO22ONCojBBZuDI2kR+x5AWQytD1tf8GsPkBKQ4C7zbwQlhzvTT7v0iPkwt0zVl0BjyDMz4V9X07uNpDoEdaJlWg/J2O+aQjsqUbZMFaKuX67cBuF/70TxCZUydrDU6K+Frjuf8zquAT9KJBPd1AOU0nAFWf8rlwuWgi9H2jiZZ9gVDHBor0P8yxv91TPFDVoUFuFpY3KrUmf+q/ZAul1cIJFKk+n12qq4KWP1D9Fo+aX63Hce6xSZhKZf9fG3n2+qT6d//G5qUyqpmKL91lVWUyai3Gr+tm0F+MPrJboVr97mB2NKSBgYZqWU98nI9T9Drh5F26O9ae0wCX3MjNxoWzt5JUxIsctSpzdGFdOCszO2Y0CxCqzdDiu/Qx8Vn4z+z/dvsG4sGxsxfbZS4XU8qWHTAazW55G4k/Jk+xjZ10gfih+qiaahv3EaimQwbqmbqPcyfxbPfZSFExKAzN5palbDzddIiFUmYRCtMecebDNk/jbworiQTvJDpR9yZGigflSkNie2w1jv1NuNO3Sp5mwsf/Ur072ov+sdI16yR5PYfLcdk7O6+mwE5fDvlqZiBJXVpJQjU15ksMUWMGdprdnr4NtdjI3xrML6O+5TaJ91+EdCzN2CGbwd2p3ObGpHr7OQTdxT90hhZ+FS4l/U8srpJr81LmzfvgUAJktPngLJMXluT8lcqo/diaYPH
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
