---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel-token: AgA1mlMb/h5ovrqpazzWjszmsv9HO0QNwctu1w6wzu1SCFn0ihstXW1sBqrcD9diDdV8DSf56GKkcWbJUH32vjz/QoJgzrWFNCB5PDyyoHvXbCg/RKLsX1XmW6akN7hLkV5jk1GkRQrxTz/qBgllib2HOAzaJjNScW84Mlv3pCinWN05de357Ur6eT/8RDHLUOaaSMOY4Zs4HkBZkDqqYoyGx7bnjjAdD6UrYYqg3sL1NmZQ3JxxPYSvyRolEG7q6D7rln7DCU5y3iA1LVtJ2VpjTFi66FoLj6wQUjUzh1e+hs8cWFahyb4ncmQ/DiTrQnoSUKBJmuoA1+AhZXv0ErBbG5/NthJogOPc94USd3KfTMH+lls5KgKK7YbWS7ZsmrM0UY0PlowPQVTXjr6m6H3WuNzfWRG/3e/HPCDObhUHG1TmczBdjpCE2ndwyDAb01QeiFdPP44RWFdLFmpxggThUHfiCwfSz+PwusvqmSqC/nsWNBUPfZHdDRuSJjaPigND4vdBMeC8Xjo6kwYq7FNNd8JDrxBSSFjmQa6TutfWYQM5BCHMYJL8c0JXybYqv68wVIqvPs36gBQklcs+T96tTtSvL619874m9wUYruY6zXK8Ys29tTDLL+wD42pNoTBZBR93Ho5CowZhaS/6BWKP+E8q2h6ad5oo2DKjwGZAlJb1FsqsEYw8njyAdMgkkuQRkTCYOHaYoil8HIYfIldmd3W7lwko12xMVKbVWRfUV+8zvl65V3qxEyqHdcY8sUxkYleSkrl+Vb+saLrm1/OPWzZ78yxlfvU/xLsR7aFa7veFwHUqmv7Rx1di8fxxoJWncNz+6Ylda9N4Ps9LefInvJAz6W8HaxvAtfTVWvpK4nbrbb0Ism2wVf0omDAg174WM1kyKt3RoWQxEscqwOME2IRDWsU/GBTh1Qp4Rhv3gcdRlJ21tbBY
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
