---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgAY/3c+coZ8U3lKQM7N3hCZRo/R/yyQZZfWlLnUpPqjkXDviik6KFYV1dRcr0W7ZEzbEulFEiLAuYF6C948v7ysuFz4Te2QrdhZvQpXWhZPh9p3I3Np6jSZpRyDloOsr++tmHdLqFP7ItTZMINHk8+2fBMVSKRx2/Pcw9OWvXSFQVIzyZl2nqSmsCv7zJJttAMbmUWnGO1XXR6Bdzkh6eW731KnkxeQLdk0ggJRc1EJhjn5HXrNm8iwOvbghXgmRO+n8F23LYc83yVKbvfI4eVOczJgjNEpTrbEbUlrjN5wm9oKrygFpLY9YY3PhvnrQN/eTmQQU9piV62k0QH7soXnSuI6K/TsNLbNEA10DxCn9ziQseUGynVgRdN4mTc2q9xuexNJIYSi5Tk8GfvWl1Cc3D8ozBHAcbkHT/2sr3ZUMfVjFG/b/cDBevXd1C8oVWDbumZd1WEhLJnfC5JtI5wWngjnnnHn124pP/J/BpBTbZl24E2jJ4wEKY0025YH9J/C8XPU8jqg6+Q1ABSa08YFPuplA7pPnU25UwahITQB5eF6DHEcYMPj929DmPQ1ov5vjk04aMeOhGG14D3C39DH8tz4yof2SCLZeu6hidNSyVW7/tsOlkDSaPZ0hvBknYdqgaIBIquH9AS5jpBGzh44i+j1ZrVPQO+Y7QQeeoc7aK3/+DbZEMOxMVyVDqBIcwE0+nuW+eZDAnxu3U2KQ5ov296Djpu64SPt3be+4PeUR4cU1eiF4j5G9jRjxgrouw+8jcIDqOsttrmOE2LL8T9B6pLBbCZIc0vjHMNTGJ/WXX9Mb84XwFQEHXJa/tipj224SIgY1G3XAFj3jZcwgZEqc1PD52AMEcCKqQOUudll7wgLcbK+tLT5EIrBOX/N5836p+mSTdImKVQJDjDOVVPS/hVwGX2dJTsZ2CUfsEhAdwLo6P2zH9BD
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
