---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgBDP3ab/lP2pl1thoBkrU9IWmyU3E7/W3y6kRBMZB6wXaKz7hjA2tERShYweAnUjZaiwC6rbZGqwuBfne7u4Y0BlRmn0JO5IERyGMtjMJzLdF41QBbCoHVP2+yRkzsxEpfTCMH/ceWz6p56a/r5F/akyRCR9o++Crvp2lNvaFtbXZox+0NzW9DUqpduaGuUH0HEnHYrbZPAcyY2JEcXJkuMgE300B9MSmU2TRxlARq2vLSj0Q7q44MVWos8kKj8mraD+U2cdUe/rqwnqctX28tXgzQZjSnpDxPiEgIN8mExoSpES6hdJ6n4TbzK6yH9CY2DQe+ppXILGW6KzpSSYD2Twy0d2vJdlNW/mhH4tZEopLNflq6heZN0SEBV31jHcL/IBsdFea4Lk1/RmwC3ceO7E7gW6YGUTOkwF8oj0WJOBm3LUjgzA1d50Kr+vSLqIhKtKhSvFuGu9WVhR3LFcJpzS5nYQGBYdvSsgonRaWUtTauVssalGs5SVFLKZb4iYV26abUDQCJy3a3yeffQVKJgVBR4w7BYRgkQus2pfCPISDfZZByou0BhXU9EUK2mGPZ5zKMLx0DsChQpP7GX7h2CuCgE5eLzlgOvp3kqUnLl5nZ4J/6+yEpC3TuQgYctG7E8kBgfQ/9EfI8rmsG07Hazh3RRksPxE+yllDTMTMGocaPnGlw/CeFSpuJmZaQ7pDXCW0H4X7hyXP1QB16WctiVTPbRmM5JWqZgfZvrsizFojRbhRL2qVZ9Yr1BOYJkWWQVmAATcLKkR3imytoZtLCVUrWTPsrmkFOdwE/agKo00699x7CF8G/kBLNwu/RuyOxRWhxvge8bvmFUD5vpvjGW01jryEwfWFoZYDKeEhmCF+Z/HYtr2kfrfu4uBYfexjOaQTCGzSxr4k7Ciil5Wx/q9qH4+J98hVh+BZy9fBVSxQ4LU1OFIzgd
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
