---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgAOoq06iC/JOhVasIzzfYf9owD35ICpqPfF2HTHlfVdDMOH+sXqaol2GPEh9JGSc2NcsnWgL9a0yZ1Jbax2q1P5diFQAPdXvQiZjVD4S33dRkTxg610Dp3+AF+scOhq2pQx6Z2dAQ3Co5z2xfanfOmpbdmGSlQ8PFaW4qOrr1k3cU+tPvMWkSoDaK1B2At6GWdKfLHz1tbmjIniB4Ki0I+WB51Ne7sqpRw734WhgfkBjSgPbmf+LWLkmNkNA/d1f1OzuYLn58YhqZ03HkNrIbeINSz5WsJv6a9sgqXeSn1taCGlxUNOHYsk6c4HP1bu0+eMVietco4xhZj29uvObWww5IYGdYgOQqdGZvq158sCuPL9yt7sAV8PDtrWEUHOgWnVxxwwWlIx6k3olgfgWc9EHNLuuRHeCZAzMpFmQodE0m4kDl7HZfoz9MjSsEi+vvT36gAJVlSHwOwZeUPztBDQnF8edJLzuFVcU2ZPDO0pfUGLZjSEnQbOTBK2S1Be0mxQQFVIsmbZSbWf2Lc0bPQJREHYfE7ZgVaiuxRXsvAM9P6gIpx+HY2Fmz9oweNLpMC6xFbxbDIbkz0MFqBDzID3voCvechKdhzeKNUloM8gM/nxFmrIU8D/oRMqXff/Gf6QiR/shhE3yyK+osQPCwyeE+iNYu8XlLAHjVUivDxhvjzAtUZHbnFyS6GTmN31VXnEjyBSvMRFhEnQG6DO7lBblQqYu78jUliN9sGvNfdV535uUbULJwOYJPXst5pu4oLSEN61dBVyojkXRSIC2XTJn5qXfUsxXYoE+8hcUKUbiEjUZE7atIxuvPM00ZihA1rZ1KmUCTB1nNeN4urmFIKuunVb+fYeBsIHs1PzsHJnLr8Q6jba06Sf1RlBmOy3Wi/n4G+fTnEl+Hm/OICBb/5CMDr6RKksG+0z6Z+81JA2zBabhium1wxs
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
