---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgCDC3lwUAi6mwR6rR5805csW/R4DurEBiEtbkToAg9ZOMLUnnmoB8QAmtUthJPDYwDlnx5Viwu1yLt2NRVHX0BbE6y6ENx/9QI2yvk9qjeksU843YS3DiZU9pjJRVUu8SgHJUcAh1jPSTyi3OWCy+m1qy5nC800KeMsDfhrCPzac4l1pPK++GnZ6gLM+NCmlu9ZZLMf85taEBmrZebJGlrLU769zryT6Ww+xNtdXYz8uwEn6IOvlZ9NWcTVxsU12Z9a7WNsEtKrK4GSyyyyvw0R+iVzlDrzOlrP1OafjYBStazpIVcYi6LaOm8A6UBnAa42Izswfsk8pvjI5/gyfOX6j9WX2JzPW6LYxJZ2xVivnnDLNlwUQgLwkLiYUjP0l3W3lfPH1k/gqcMt9Mub3rn/GKkOY0agVXxorAeDnVcDba9JVMIocGTueLlefpTF/OWEpDKEJjr991OVP8Xw13paO2iEXVCPlVRkLWtLuTIJtgKl2GqmMZQtZFtqkJL9QsQnpSXSVLcN3hjF6SQsEuwBB5uaAWJK8/4ZeFXRWWK8Z+1EZhs+FHy47CGsR7V4T34KTYB9Q+uOcn6baBWBpEn3kV6j1AbGFhY1q9ulHFTEMKCieqTJRoFPfG7mkY8jyQ+IEqyHPpch5dWDOAUFN2ss2pQyNf83PLYAcRj5h9DIlbrYrsFhfw3Cxhd6dSQ3zGYsx3z1Pn0N9GXIIiBc7VSkfuGwiHlDRJwPJdvff2AY3kC/hXB1X/C+JwhCCB7IQsu6/zQ5aOji7UG7rE3W9pKk1FHV2mOAd5LaCXsssaFOv9QyGzxD0FvAMZ1WVBu3nMC9X8aqf02JRNKfNMidezHLxbLoFEkdPymmhXY//2DDQwCZe4UuPnMo8hWgju5LHRqSmVLOWJJIT5YGYk1iUzrqfHm6WAuxtxgUYbZq58OjdtkG/2aJQnwa
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
