---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgAVgPbx8E8N/57pMxp9LUyX9jHBA2//MWhCByl6uUKoR//ILVivEy7Ym/9CCG7DuzAOBm1mbDKPUvjRFTLtnqK/UNPIli1M3A0tte3xGBgRa5AHl4VbwaQW4fDtZvKTSavniS9Q+ew2kI/qc/RVxTKK36FNBttYfArRTyQ0oWpFVbLvCiK+o/uBwC1Qx3TCcIlaWk7Jhxzq1S+mpCnTpCrPNclYEWVNFGbtE69K4DejU49er1VmtBr/IX0R1NyvIdOtQcRgOuKy4WLtoHn84s8LhhADoNeunA3FsY2q05zq3sTRyTVGKdDRe7jmEYGN2NmM1bTNI2n5A7Ig9xcVZsDJaUbBX0dlIX9KCHyqrmZ4dU4v7lB1WA6RLkPuf9wJ/46Y3LghZwF8KB0h4bVgOVChq8bivonANLrY/1JIKLtMQ6KrIKk2GKw0yabijtIPMMQlBgWkh4S06Vd2uPq982g2q7YQylynDw+sd0gtUfIEtqhAXQfLurWsSb6vLaTCUbBHVOApIq1qp05VpZhxgrx09IEpXaODnfQuMiFOPkWaZ+Irw2L+5Y1vPjV7vo+sHTFjvDpMX8dmTgf2aFPjW4Jfx4kojBGtupbqTLBmkkUyH1A0W/OzG9rDhz6AGk7Ayy5lioI3v3bFz3pLNc7h6+5HVFowsKKdKbq6jW6PNfaMSmQEeT3jN0jxG+STFjM5H3ciSbmXzrTTfz2wIuSf4o2WEk53Bh0Kr26if9t1TO5BYO3M/KjlTl/ZzIhJ/JLCBI9XceiUs3J580G1Hp5zwL6opD/Nn9pzcFaC6MbStLYN5dbvdlaJdAvl8I1jghfGsKLayyghqHxNst55j1In6JEkOd1LnlIQQphna5yhrwDWMwAJlGWY5p8KMFSAIgh05X48fHFVV5hT0h8Ily1O9X+qp4RlW8lkEw7w8khkrMJWiuMImyMOAir8
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
