---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel-token: AgBK546u5dlrMrSyvK8FRplYApP/sjrDKh1O/FqZCHG8xX+cwDDiFLmvFa931t+42YfZ4ppRWJKYekD0IvCvs9xroP5SpiSnBsSAA+Jq0a4mhwkS76x9eADns4pFfufhT0Nhjw4pIfcz9k37YHjvD9LMKSsxW+Z5OMOMn+/RcRw9pBju9d2k3/BJvNznXUlVSByBBTu8jFWWNFMe8J5VaL/XyHWvUJc+eh5hSNslVVE0G6BTEt3lzGVEeYqyqhTXG7L7mDjlI8jeSIM61N3Xl1rtN4GHCZQ69Bn4FyjfqR8Mj2ADDS0jvyNAALj/3o9wD37WwNvb8NeV1NFBy2HbxPvrgUu59uK3t7yHQXg2vRP1fvsUJYzLC3yvNKBBODVc8RZAPhaONclSbI6mFvGBKu64bQa02ajjLU6AQmPCaiKnHOVvEuU6Ww3B6KBhsMpen5x2xgCknrNWazV1xEyO1fhreWGc+DWIFt/IZ0z7Ljhkn6QcwLQ0ScoI9boLqjA1lEv+Svf4atz++uC8qWccgrtjKwfi9eH2pCDaaulqPIQHdzd9Svlrz906+UjuUdxHDBeOB89VTmI+oT/7PqFkPThfvHdbvkCZbhIsfiI+FfyF1gfI2Fpr+sLTsIx2QagUVvust55g5CUsG/6BuJ1N1UUiCdk3y4OQuCH7ymmcUUZpwDaQSrL6o6CcZfNqV/1jUxmmF+xJG6bluRQClDtKbmp6e2ki4uQ9wmo5XaVw6qRJIqnCM5NINz7+gbrFqEk7MWuz0vzk57JuwLEE/aZ8VW1ONGlfAvZ99OVGHCbG+OqGiDKCCaGSe8C+A7ayHCBoV/GWs05f8YLT3qaWN6w1j4dGC5j2olp56qy2kO9vZuc5hWnl0n4yPoL/MH60vdzToiieVuWBVG+PN8o6Uvytd4PJSSIEKtJSdpH5C7WD0fTUkm8BwPj1B5en
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
