---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgARKSrdHvB87QtkQcmXrOUdUuyW/cWiJm9ZSFehHMACHnQ24NYWwfAHxWIBrTJ6G0SJ/UpaUWmM3MEHlc2ot6BdxxwV2dw7cINMF1Zt6N2vKZUyFOBauQNSP0efd5NdnHEZmPs/UeNFRc2dH2wGKDaDbriPMbV7i1X/2Fm8ZtK5Us5myvgZd1M9Z5RcWeEhgvvd5YaHwVazZquMgxH9+MmjlKw7Mbl+q2xmfRlvikFZ7GlvAr5emVuUxFfZ/LMU0QV07ncd/F91Ie94xeyZ9xIiRC/TMlZeEHwQQfHx/Gmtayc4jMOhPLx/i4CvmzWfhg5fMmeEAf+hCM79K6ZuAxebrgx6mjcCwBg8GL7OcPvE29JxFS8S/tHlWEMeLK4zfjXZTLcH26U+2OBTeUxxwftwzC5EkjkYrIszWcraj88MciXd1B36u9wFH/t2c3CYru7x6L9t+YoF/oDbNZb6X84AMPAZGZrtMREazFjnvlTg2a22Qd7/+v6wBMvOIVuHkZyfm5rtVE9xX6HdVgc+Hc8YVutOJEMMMhEWmcqOET9HL5UG9te+UebuW82iVj1gFlJuwxz7RQUbcBwlLWjk2Wa2i5mjxFQg0lMeObpDqdM+Cs5HiMVszVSpv/cxKae77RRMKBdTZJEQaVaZc25gQGodAADBjkn9DADscT3ksSHzlKV0THoSZSY9gBXqn1Ixs5ztc+nUr636V1BQXI3Z75iexDn4rqqoXMGYtanXIDYlgl5ZAAUUVcUXXZuD2pRPZQrRmiSRlYmeDDrdtBhf6XNBmAFdxS6GLzAnJcIJBuEilS7+YFzA63cpUPg4bT+LznIJoU26a/NExyr17cidtVY7/KeL0b8t1yieVKOUE/Qz7aTZTgWabL6mgaXBHNxCdJq0EIlfzptvcJQke86FFevnux2Pju7MdAo6ESYwc+gT56nzvzwQlRuD
  template:
    metadata:
      name: cloudflare-tunnel
      namespace: cloudflare
