---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgB8FpMuR5XN3H2Q/bx3roYO8ELX81FJNaJzbudRZb3zJI/3mA+EM5yqXMvR+LvxuynfIUZXmSc8bi+5GCV4YZqucvo+h3zDQvHb+MkXoNe2o+csoSjR35Nd17OeEVoUG2hJULnH7v6kYZ4N5SyKJxGDRJDWQ1EH0sE8fATpKVR3FmHZlzhyps6oB7CYeaAgFMoUmQgUNpphRvBm7kw8CfhtMVW8X93g4toyIbw8dWQS8Us8d9A1JxfBr0aO4TJdxHNJEaLpiTc5RZ+xb/XeAXKJtRiiqd2eqflcSTUxLT+hHAK8GrlwD7Zz/nZ+CgfJg45Yp6OatLn4ciqKDSHQVdCj3jW4OJDdI0U1XviKcjyU+rMutTPxNlOLTlayPFPlJ213aaZJc6ihJd2gFh+VbSRfg32ai+LcaQpDfSVDbA+DoUVeZ8IXlYF3Tx1tKUXajOea9VZJKew7ZQyteOhbX8eomdGBb6vaUIiwlf4oBKrB8YiGy39zckNkeCp2aYwAc1j6p/g82JIazDsj1p9Ah+TZWPoUzJOYkcE2mFThJK9L6KMgfZMLfMT9HAogFuyeCbClpyDMhPLNn7bxbfFvtgWRNwPWR+zJARs1W9oMLqjppy/14C7yfukNAcF8cCUMTLQGK4BP3Sgep6g1hniIjm21djCcpavrjP6rIKevSVYnKilGvpAj+DmqbZU32ovnBn6zlprdbIS56ouaJa6po/YP7sqnLRZ5Ld6SYnb7t7a+OWj/fDwwCNinsRHQew2D0idxp151Iib5+U8XN7m1Ux3oTpARNXXaFj7ifO0OcI9hLiRUH3sHqZhet6G+TyJg2Bazdj/HYw5hLYUiJ68lKpk6FjTWVOGp0LNqhy18wv/Gd7tZNHXI7VBiHHYHm0fcc/9sH2HorlMSjoRg8RWWtXakudiPBxr82CeEm2X7moM5g1f9KJmfBvlJ
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare
