---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel-token: AgAhwHmFJ6KF0nBB5ce1uEKYeoKS3w6KhnPhbephqYSz2yyZgihrgIVOs5NKf3okuBor9KCmUzlXa9cdFmqp49VlSCD/7hBSCSvEuHesy3c8RELmi2senStPReUslXqP2Y1cWaGh3e8t/wLGQxk/R9MfpCcYDKyXGNqyi5VFB4bavgTq+DXKHkxXSmWP3/9gTeeM9/HJttVEZwqX8cKVLnDUdG97Ne8I2REbHCMq8HjZ8aT/KpFJmFNvXbMTMzIsgkLVhLCnFd9R/RDfYK+rjHoHLU9rBl7nZpIAErII8HtvTJg5lyShpw5uiyxT+ertGxyb5TNKb2kaCUrXMi6FrBQUL8YHVri6mfniZPodYq7Ar9EfXqSLeM/4XApOt3ka39b0R/qv2mnWo2AgS/zzo9Py4joFZ5Ua1cpYWN1UCb2Y42kfS6MSn2vQqHP0NNRD1OQjnn8opNINlzjyKDgVs8fSxHpGkPwB+MA4xRVAh3hBekdihNXQc3TQ3YbBLLXMfJW8+iviLrGee6XAvUtYch0id4JQa3whpKO9A4WJZ04qQzB6gVWgPrCyf+5qCXRcs1F5hQgooBVdtUX8SWQ6xzoQdrBtNBDpt+WWxq7i5JQxwQbHQtfqsnv5+O+irnbxi71cqW4NljvJd15ZWmUpUQeQmeucUzEZqWpaQ7U5QdBZURgji/F/JafdPUWoEtT4dSC2/JMIx+xRny+Jn0ed5rzOeyS25htTcm+B+3vwZAdp52/GwWejYTIxlOS07UuXDW0RSfSC/Cm85LXSq9JS6yk6z/+jDss2lXSzfIv3x0eWgnu8XfKUwFP/jwKEHsQCos5k0snc6ksthSPyhBf4pqedsx/A5vxh9Gp0SfK+BtmYD1DAl5m2kBKMDkzAmmBI9GMCHQNAGHLsdcjd3/5nTp3QgVW0Bw45nxGnyOMPBiMi7K4zTFYorOng
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
