---
# Cilium CNI installation (HelmRelease or manifest)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      version: "1.16.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    hubble:
      enabled: true
    kubeProxyReplacement: strict
    # Add more Cilium config as needed
