---
# Cloudflare Gateway installation (example manifest)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cloudflare-gateway
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-tls-cert
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All
---
{{- if and .Values.cloudflareGateway.enabled .Values.applications }}
{{- $serverlessEnabled := false -}}
{{- range .Values.applications -}}
{{- if and (eq .name "cluster-serverless") (eq .active true) -}}
{{- $serverlessEnabled = true -}}
{{- end -}}
{{- end -}}
{{- if not $serverlessEnabled }}
# Only create wildcard route in cluster-init when cluster-serverless is NOT enabled
# When cluster-serverless is enabled, it manages its own wildcard routing to prevent conflicts
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: default-wildcard-route
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  parentRefs:
  - name: cloudflare-gateway
    namespace: gateway-system
  hostnames:
  - "*.benedict-aryo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argocd-server
      port: 80
      namespace: argocd
{{- end }}
{{- end }}
