---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"  # After basic infrastructure is ready
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://knative.github.io/operator
    chart: knative-operator
    targetRevision: "1.18.0"  # Use a recent stable version
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true