{{- if .Values.metallb.enabled }}
---
# MetalLB HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  url: https://metallb.github.io/metallb
  timeout: 60s
---
# MetalLB installation (HelmRelease)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      version: "0.14.8"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    speaker:
      frr:
        enabled: false
    controller:
      enabled: true
---
# MetalLB IPAddressPool
{{- range .Values.metallb.addressPools }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
  namespace: metallb-system
spec:
  protocol: {{ .protocol }}
  addresses:
  {{- range .addresses }}
  - {{ . }}
  {{- end }}
---
{{- end }}
{{- end }}