apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # KnativeServing Health Check
  resource.customizations.health.operator.knative.dev_KnativeServing: |
    hs = {}
    if obj.status == nil then
      hs.status = "Progressing"
      hs.message = "KnativeServing resource created, waiting for operator"
      return hs
    end
    if obj.status.conditions ~= nil then
      for i, condition in ipairs(obj.status.conditions) do
        if condition.type == "Ready" then
          if condition.status == "True" then
            hs.status = "Healthy"
            hs.message = "All Knative Serving components are ready"
            return hs
          elseif condition.status == "False" then
            hs.status = "Degraded"
            hs.message = condition.message or condition.reason or "KnativeServing is not ready"
            return hs
          elseif condition.status == "Unknown" then
            hs.status = "Progressing"
            hs.message = "KnativeServing status unknown - components deploying"
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for KnativeServing Ready condition"
    return hs
  # KnativeEventing Health Check
  resource.customizations.health.operator.knative.dev_KnativeEventing: |
    hs = {}
    if obj.status == nil then
      hs.status = "Progressing"
      hs.message = "KnativeEventing resource created, waiting for operator"
      return hs
    end
    if obj.status.conditions ~= nil then
      for i, condition in ipairs(obj.status.conditions) do
        if condition.type == "Ready" then
          if condition.status == "True" then
            hs.status = "Healthy"
            hs.message = "All Knative Eventing components are ready"
            return hs
          elseif condition.status == "False" then
            hs.status = "Degraded"
            hs.message = condition.message or condition.reason or "KnativeEventing is not ready"
            return hs
          elseif condition.status == "Unknown" then
            hs.status = "Progressing"
            hs.message = "KnativeEventing status unknown - components deploying"
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for KnativeEventing Ready condition"
    return hs
