---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token: AgBU4qh6ollGxKhnBjFBH7r5IkfvqSki3pg4dfe/vZyX0fGzoXtHplCeu3dPFwbFopd7ayXnkz+pxSEa+rYuMVXSq66f1YrCnhdYVaDJ3RsvKnduRzcuIcyUOSmiTzYT1xR0nCpoOsOS/Bz5hOdi5waKhoVKYQ34Pa6Qx2sPdOBwqOARvJZg1KTfTYexAxKlvvrtBxozyjCH81ng8yRUvKjSc8WFg1kiPi+CemtocpbUBb3J7p3UqAvPIkq8jqa7hXBMd6kZuiqoPa6AYK8GidiC6Qqv4g6sszUz3u/2DFNpLte01EiqrLOfTmCc7tPy3vGVufDOTALTV/aXQgok1dZ6+3Sf5mCSkUpEaoRJlxHbOK3iTJrt+15k68WUDST2UjEvvhV6sBx7wnCdyGyhoNr61z+3T7a9tJFSTx8TdCWUojCB8g+97mR9OBrpoS6vChyhoq3phLC/qTGRmGWA4ZPgchJGJDx5obnMdPO5P819Lro4iBhMcBtTktslr+9hFkLS+nYrBeP4En/arw0GmaXMY4CsHTcGWrx7VfNUK6RdZV92/exXd3slGubUlxCC2TG0mVsTl0qtAx29WSD/NaToVBBspagFFq+tBgpkI5cifHazCvj8WMOvjFSoYdqXpNSrnpplWqzbVs0SkxBCPWPDZp4wzgHFpa5aPNGtS6CYFmLMp9qx38nB8jm4ECwRF5fPRMUIWL1QW7rK2rXhio2E3Yrihq7OpS+pjt/P5UsYHuV6Vn869/JTVspEdJm/CTcKGSrS6Qp883i816ocAPfdSjgPAz74R2AIHuTwJpxQNicn+zZ85mDAbtb0G0Pvu/DyOLB7Wx9fdZbNqOk9woZkhBk4jVrImg9urgBkAtum8N/ybi9yIuErRH41r1PBHCbTfStIYL+DiGw5Cs3XoutU+DmKxOin0DZZePbIqDdCbMtGmqR/9iiV
  template:
    metadata:
      name: cloudflare-tunnel
      namespace: cloudflare
