---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBK6wKVZJGJbnoCDquxKyp+zE70ys2m/TOGNbgsPtu0B56g6gd2rLSFj5BoIGjvMH64zNM518TW+E3VS272319kWZv4C5sLgAXG/oAZJ6auwo1xxPk2K8FzS/rJUfFsDfi0tz8xxqB1j52ltEqGl0v+hQ8hoc34t9rJ+cr3ju10Q5Ac3RNfhJBhTVpFonb6/BaZUAk0d9/oPqn/Ku4TdwcYM1rIV8iUIqit+T9ubOo2KTfbL3hLkzTgJAFskRGA6c8cjBnVRxHkG88h+wSOix+SEcE4VpV8dl6lfCIKJ58GI/Tq7Q7EPgeRZ/M6ToXTxg4le3OWiKnrP82HO9wEZ7M/rgJ3uGBUnB8Is3RIiiD7J7MHF/za+Wu8wjLGLy2zJPpLcHl+j8JHX33ObR2OG+oOZEVryl5QMpgZmkA2ElHTvGsHARZW1CvemDxWJbNF2MGla7KRSKTG/oprDzpJP5/1j/BhAv6H0o7pzVL4mQ4r1CweY3jQqu9WnEtU3/GC6vhpU19bduT/kmXKeToN6l5Cr7xyjYQG4uhSuBEdd6jrNRtNwRTkPuipFtRua/kU8BC8/MVVKjkhPwG+OGD/3E6W626FW2E+n3oeo3dAndNpCBTXiJnt7l8UVWMTopmxWIP7jI6UmhDYUcZJ5Ykah7UdQjXW63zNcgyjIqKRiJ+sRyRcckTUei7dwHyK720XK6NkUFdYarT/un9rCkb//5w/xV1zKl9r3+Z/xY/+tX6Tu1a1MgpeTKt95XPnhHfz4az+iLz44TehzX4RJuhv+dfezly7smLYsSe8Ylp5jcw4IWhwQb/HdguADtt2g4pHZk0EmdxzeXE8kNitoQcVZlGAGWsavBzsLK1S22XzA0gTD2luMFB5gCCflHan6EZ9jyYB1JLOcLx2G3aiCW7P5SsquX2JptALNeDgmLzrwGoOga9OYYGXWIQA
  template:
    metadata:
      name: cloudflare-api-key
      namespace: cert-manager
