{{- if or .Values.certificateManager.enabled .Values.cilium.enabled .Values.metalLb.ipAddressPool.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
{{- end }}

{{- if .Values.metalLb.ipAddressPool.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
{{- end }}