{{- if and .Values.argocd.httproute.enabled .Values.certificateManager.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parentRefs:
    - name: cloudflare-gateway
      namespace: gateway-system
  hostnames:
    - "{{ .Values.argocd.httproute.hostname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: argocd-server
          port: 80
          namespace: argocd
{{- end }}